### ISSUE TITLE
Control sniff for function doc block comments

### ISSUE THREAD

**Issue by andygrunwald** [typo3-ci/TYPO3SniffPool#32]
Lets check if the function doc block comments are checked as expected:

```
/**
 * @param[space]integer[space]$foo[space]Description
 */
function foo($foo){

}
```

Maybe PEAR.Commenting.ClassComment is a solution.
Check  [Feature #9863: Reimplement PEAR.Commenting.ClassComment](https://forge.typo3.org/issues/9863) for details

Further more what about short / long types?
```
/**
 * Initializes the plugin.
 *
 * Checks the configuration and substitutes defaults for missing values.
 *
 * @param array $conf Plugin configuration from TypoScript
 * @return boolean TRUE if initialization was successful, FALSE otherwise 
 * @see tx_myext_class:anotherFunc()
 */
protected function initialize(array $conf) {
// Do something
}
```
Check [Feature #38688: Create sniff for function / method doc comment long types](https://forge.typo3.org/issues/38688) for details

**Comment by wmdbMattes** [comment]
In regards to long or short types: we stick to short ones

**Comment by Konafets** [comment]
Fixed in https://github.com/typo3-ci/TYPO3SniffPool/commit/2120d4f1aa53aead3b8d4123d36f3b3ba51ad320
