### ISSUE TITLE
Activate sniffs in Jenkins

### ISSUE THREAD

**Issue by andygrunwald** [typo3-ci/TYPO3SniffPool#33]
If we adjust sniffs for TYPO3 core we can activate several sniffs in [Jenkins](https://ci.typo3.org/):

## TYPO3.Files.IncludingFile
Adjust excluding files for this sniff as well:
* index.php
* typo3/init.php
* typo3/cli_dispatch.phpsh
* typo3/sysext/install/Start/Install.php
Original ticket: [Task #37492: Exlude some file for TYPO3.Files.IncludingFile](https://forge.typo3.org/issues/37492)

## TYPO3.Strings.ConcatenationSpacingSniff
Original ticket: [Task #39018: Activate CGL rule "TYPO3.Strings.ConcatenationSpacingSniff" in Jenkins](https://forge.typo3.org/issues/39018)

## Squiz.Classes.SelfMemberReference
Original ticket: [Task #41257: Activate CGL rule "Squiz.Classes.SelfMemberReference" in Jenkins](https://forge.typo3.org/issues/41257)

## TYPO3.ControlStructures.DisallowEachInLoopCondition
Original ticket: [Task #41212: Activate CGL rule "TYPO3.ControlStructures.DisallowEachInLoopCondition" in Jenkins](https://forge.typo3.org/issues/41212)

**Comment by Konafets** [comment]
Jenkins down atm.

**Comment by andygrunwald** [comment]
Afaik Jenkins won`t come up anymore. So this is not needed anymore.
