### ISSUE TITLE
[BUG] Check for default switch case is redunant

### ISSUE THREAD

**Issue by masi** [typo3-ci/TYPO3SniffPool#46]
TYPO3SniffPool.ControlStructures.ValidDefaultStatementsInSwitches
TYPO3SniffPool.ControlStructures.SwitchDeclaration.MissingDefault

These two rules/messages check for the same issue.

**Comment by Konafets** [comment]
Removed the redunant check from standard at https://github.com/typo3-ci/TYPO3CMS/commit/4ab79427e3dda0a2b90d9f4de86a179d604c93e3
