### ISSUE TITLE
PHPStorm integration shows @return void "error" only once per file

### ISSUE THREAD

**Issue by wmdbMattes** [typo3-ci/TYPO3SniffPool#49]
I tracked this by just testing 
`typo3/sysext/about/Classes/Domain/Model/Extension.php`

Result as follows:
![bildschirmfoto 2015-02-01 um 18 24 28](https://cloud.githubusercontent.com/assets/2158054/5993075/2f4c74e0-aa44-11e4-8ed6-74646663b625.png)

**Comment by mostwanted1976** [comment]
I could reproduce this and discovered this behaviour:

only those setters (without a return annotation) that are placed before the first getter (in that file) will result in a phpcs warning.

**Comment by Konafets** [comment]
Fixed in 2120d4f1aa53aead3b8d4123d36f3b3ba51ad320
